/**
 * mockData.js — Seed data for MediHire Healthcare Job Portal
 * Pre-loaded healthcare jobs and demo user accounts
 */

const MOCK_JOBS = [
  {
    id: 'job-001',
    title: 'Senior Cardiologist',
    hospital: 'Mayo General Hospital',
    location: 'New York, NY',
    salary: '$220,000 – $280,000 / yr',
    category: 'Doctors & Physicians',
    type: 'Full-time',
    experience: '10+ years',
    deadline: '2025-10-15',
    postedDate: '2025-07-01',
    urgent: true,
    description: 'We are seeking an exceptional Senior Cardiologist to join our award-winning Cardiology Department. The ideal candidate will lead complex cardiac procedures, supervise residents, and contribute to our cutting-edge research program. You will work alongside a multidisciplinary team in a state-of-the-art facility with the latest diagnostic and interventional technology.',
    skills: ['Interventional Cardiology', 'Echocardiography', 'ACLS', 'EHR Systems', 'Clinical Research', 'Patient Education'],
    benefits: ['$280k base + performance bonus', 'Full medical, dental, vision', '6 weeks PTO', 'CME allowance $5,000/yr', 'Malpractice insurance'],
    icon: '🫀',
    color: 'from-red-500 to-rose-600',
    applicants: 12
  },
  {
    id: 'job-002',
    title: 'ICU Registered Nurse',
    hospital: 'St. Jude Medical Center',
    location: 'Chicago, IL',
    salary: '$85,000 – $110,000 / yr',
    category: 'Nursing & Midwifery',
    type: 'Full-time',
    experience: '3+ years',
    deadline: '2025-09-30',
    postedDate: '2025-07-05',
    urgent: true,
    description: 'St. Jude Medical Center is looking for an experienced ICU Registered Nurse to provide exceptional critical care to our most vulnerable patients. You will monitor hemodynamic status, administer complex medication regimens, collaborate with intensivists, and mentor junior nursing staff in our 32-bed Level-1 trauma ICU.',
    skills: ['Critical Care Nursing', 'Ventilator Management', 'ACLS/BLS', 'Hemodynamic Monitoring', 'IV Therapy', 'Epic EMR'],
    benefits: ['Sign-on bonus $15,000', 'Night differential pay', 'Tuition reimbursement', 'Retirement 401(k) match', 'Shift flexibility'],
    icon: '🏥',
    color: 'from-blue-500 to-cyan-600',
    applicants: 28
  },
  {
    id: 'job-003',
    title: 'Clinical Pharmacist',
    hospital: 'HealthFirst Pharmacy Group',
    location: 'Boston, MA',
    salary: '$115,000 – $135,000 / yr',
    category: 'Pharmacy',
    type: 'Full-time',
    experience: '2+ years',
    deadline: '2025-10-20',
    postedDate: '2025-07-08',
    urgent: false,
    description: 'Join our integrated healthcare team as a Clinical Pharmacist, playing a pivotal role in medication therapy management, drug utilization review, and patient counseling. You will collaborate with physicians and clinical staff to optimize pharmacotherapy outcomes for diverse patient populations in our 500-bed academic medical center.',
    skills: ['Pharmacotherapy', 'Drug Interaction Analysis', 'Patient Counseling', 'MTM Certification', 'Clinical Documentation', 'Oncology or Critical Care'],
    benefits: ['Competitive salary', 'Student loan repayment assistance', 'CEU reimbursement', 'Flexible scheduling', 'Research opportunities'],
    icon: '💊',
    color: 'from-emerald-500 to-teal-600',
    applicants: 9
  },
  {
    id: 'job-004',
    title: 'Lead Radiologist / MRI Specialist',
    hospital: 'Apex Imaging & Diagnostics',
    location: 'Houston, TX',
    salary: '$140,000 – $175,000 / yr',
    category: 'Radiology & Imaging',
    type: 'Contract',
    experience: '7+ years',
    deadline: '2025-11-01',
    postedDate: '2025-07-10',
    urgent: false,
    description: 'Apex Imaging invites board-certified radiologists to join our specialized imaging team. You will interpret high-volume MRI, CT, and PET scan studies, provide timely diagnostic reports, lead a team of radiographers, and consult with referring physicians. Our modern facility operates 3T MRI machines and AI-assisted diagnostic tools.',
    skills: ['MRI Interpretation', 'CT/PET Scanning', 'PACS Systems', 'Radiology Reporting', 'AI Diagnostic Tools', 'Team Leadership'],
    benefits: ['1-year contract renewable', 'Housing stipend available', 'Relocation assistance', 'Malpractice covered', 'CME budget $8,000'],
    icon: '🩻',
    color: 'from-violet-500 to-purple-600',
    applicants: 5
  },
  {
    id: 'job-005',
    title: 'Pediatric Medical Assistant',
    hospital: "Children's Care & Wellness Clinic",
    location: 'San Francisco, CA',
    salary: '$55,000 – $70,000 / yr',
    category: 'Medical Assistants',
    type: 'Full-time',
    experience: '1+ year',
    deadline: '2025-09-15',
    postedDate: '2025-07-12',
    urgent: false,
    description: 'Our beloved Pediatric Clinic is seeking a compassionate and skilled Medical Assistant to support our pediatricians in delivering top-notch care to children from birth through 18 years. Responsibilities include vital sign collection, vaccine administration, patient intake, scheduling, and providing comfort to anxious young patients and families.',
    skills: ['Pediatric Patient Care', 'Phlebotomy', 'EHR Documentation', 'Vital Signs', 'Vaccine Administration', 'CMA Certification'],
    benefits: ['Career growth pathway', 'Full health benefits', 'Child care assistance', 'Transit subsidy', 'Wellness program'],
    icon: '👶',
    color: 'from-pink-500 to-rose-500',
    applicants: 31
  },
  {
    id: 'job-006',
    title: 'Senior Lab Technician – Pathology',
    hospital: 'BioLab Diagnostics Center',
    location: 'Seattle, WA',
    salary: '$65,000 – $82,000 / yr',
    category: 'Laboratory & Diagnostics',
    type: 'Full-time',
    experience: '4+ years',
    deadline: '2025-10-05',
    postedDate: '2025-07-14',
    urgent: false,
    description: 'BioLab Diagnostics is seeking a Senior Lab Technician to perform complex laboratory tests including hematology, chemistry, microbiology, and molecular diagnostics. You will maintain quality control protocols, calibrate equipment, interpret results, and collaborate with pathologists to deliver accurate and timely diagnostic reports.',
    skills: ['Hematology Analysis', 'Molecular Diagnostics', 'PCR Testing', 'LIS Software', 'CLIA Compliance', 'Quality Control'],
    benefits: ['Performance bonuses', 'Certification exam reimbursement', 'Flexible shifts', 'Health & dental', 'Stock options'],
    icon: '🔬',
    color: 'from-amber-500 to-orange-600',
    applicants: 14
  },
  {
    id: 'job-007',
    title: 'Mental Health Therapist (LMFT)',
    hospital: 'MindBridge Mental Health Services',
    location: 'Austin, TX',
    salary: '$75,000 – $95,000 / yr',
    category: 'Mental Health',
    type: 'Part-time',
    experience: '3+ years',
    deadline: '2025-11-15',
    postedDate: '2025-07-15',
    urgent: false,
    description: 'MindBridge is expanding its therapy team to meet growing demand. We are looking for a Licensed Marriage and Family Therapist to provide individual, couples, and group therapy using evidence-based modalities. Telehealth sessions available. You will be part of a supportive, supervision-rich environment with excellent work-life balance.',
    skills: ['CBT', 'DBT', 'Trauma-Informed Care', 'Crisis Intervention', 'Telehealth', 'Electronic Records'],
    benefits: ['Flexible telehealth schedule', 'Supervision provided', 'CEU support', 'Peer consultation group', 'Competitive per-session rate'],
    icon: '🧠',
    color: 'from-indigo-500 to-blue-600',
    applicants: 7
  },
  {
    id: 'job-008',
    title: 'Physical Therapist',
    hospital: 'ActiveLife Rehabilitation Center',
    location: 'Miami, FL',
    salary: '$80,000 – $100,000 / yr',
    category: 'Physiotherapy',
    type: 'Full-time',
    experience: '2+ years',
    deadline: '2025-10-30',
    postedDate: '2025-07-16',
    urgent: true,
    description: 'Join our dynamic rehabilitation team at ActiveLife, one of Florida\'s top-rated outpatient PT clinics. You will evaluate and treat patients recovering from orthopedic surgeries, sports injuries, and neurological conditions. We offer a collaborative team culture, modern equipment, and genuine career advancement opportunities.',
    skills: ['Manual Therapy', 'Sports Rehabilitation', 'Neurological PT', 'Dry Needling', 'Therapeutic Exercise', 'Patient Documentation'],
    benefits: ['Student loan support', 'Continuing education budget', 'Partnership track available', 'Full benefits package', 'Gym membership'],
    icon: '🦴',
    color: 'from-teal-500 to-cyan-600',
    applicants: 19
  }
];

const MOCK_USERS = [
  {
    id: 'user-admin-001',
    name: 'Admin User',
    email: 'admin@medihire.com',
    password: 'admin123',
    role: 'admin',
    registeredDate: '2025-01-01',
    specialty: 'Administration'
  },
  {
    id: 'user-cand-001',
    name: 'Dr. Sarah Johnson',
    email: 'doctor@medihire.com',
    password: 'doctor123',
    role: 'candidate',
    registeredDate: '2025-06-15',
    specialty: 'Cardiology',
    appliedJobs: []
  }
];
